permissions:
  contents: read # for checkout

on: workflow_call

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        id: setup-node
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Install dependencies
        run: npm clean-install

      - name: Run unit tests
        run: npm test
